// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiVrEDgdBlxcUtZx7aiJd-5jAt216V0U',
    appId: '1:449590065627:web:f34727fde53182398c8ffe',
    messagingSenderId: '449590065627',
    projectId: 'flutterfinal-ridevoyage',
    authDomain: 'flutterfinal-ridevoyage.firebaseapp.com',
    storageBucket: 'flutterfinal-ridevoyage.firebasestorage.app',
    measurementId: 'G-RPNBT1RXJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBop5_wWuOGSOLRHdWm5ccrzf5uaFJBdTQ',
    appId: '1:449590065627:android:8c3f0c37d5b0cb298c8ffe',
    messagingSenderId: '449590065627',
    projectId: 'flutterfinal-ridevoyage',
    storageBucket: 'flutterfinal-ridevoyage.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCiVrEDgdBlxcUtZx7aiJd-5jAt216V0U',
    appId: '1:449590065627:web:9cb0950d7cac111a8c8ffe',
    messagingSenderId: '449590065627',
    projectId: 'flutterfinal-ridevoyage',
    authDomain: 'flutterfinal-ridevoyage.firebaseapp.com',
    storageBucket: 'flutterfinal-ridevoyage.firebasestorage.app',
    measurementId: 'G-NDD24L93EF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd2j1mJMxbhpHidx6amVTCWRPkj1-Sjm0',
    appId: '1:449590065627:ios:67b3597c2127168a8c8ffe',
    messagingSenderId: '449590065627',
    projectId: 'flutterfinal-ridevoyage',
    storageBucket: 'flutterfinal-ridevoyage.firebasestorage.app',
    iosClientId: '449590065627-j0anp6ff1thhovugk9h1h6v6ftr7s991.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd2j1mJMxbhpHidx6amVTCWRPkj1-Sjm0',
    appId: '1:449590065627:ios:67b3597c2127168a8c8ffe',
    messagingSenderId: '449590065627',
    projectId: 'flutterfinal-ridevoyage',
    storageBucket: 'flutterfinal-ridevoyage.firebasestorage.app',
    iosClientId: '449590065627-j0anp6ff1thhovugk9h1h6v6ftr7s991.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

}